# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/nishimi-ya/"

[social.params]
icon = "brand-github"

[[social]]
identifier = "bluesky"
name = "Bluesky"
url = "https://bsky.app/profile/nishimiya.my.id"

[social.params]
icon = "brand-bluesky"

[[social]]
identifier = "mastodon"
name = "Mastodon"
url = "https://layer8.space/@nishimiya"

[social.params]
icon = "brand-mastodon"

[[social]]
identifier = "rss"
name = "RSS"
url = "https://blog.nishimiya.my.id/index.xml"

[social.params]
icon = "rss"

[[social]]
identifier = "lastfm"
name = "LastFM"
url = "https://last.fm/user/nishi-miya"

[social.params]
icon = "brand-lastfm"

[[social]]
identifier = "matrix"
name = "Matrix"
url = "https://matrix.to/#/#nishimiya:matrix.org"

[social.params]
icon = "brand-matrix"
